remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: GFDSVFDGRTDEGR
description: [A short description of your site's purpose]
show_downloads: false
github:
  is_project_page: false
