remote_theme: pages-themes/slate@v0.2.0

plugins:
- jekyll-remote-theme

title: Pavel Okopnyi personal page
description: [A short description of your site's purpose]
tagline: Pages website

show_downloads: false

github:
  is_project_page: false
